Spring boot 02
antoniukivan/spring-boot-intro pull request #2
Opened 2021-03-02 13:38 UTC by antoniukivan

2021-03-02 13:55 UTC, YuraBondarenko requested changes

2021-03-02 13:55 UTC, YuraBondarenko commented on src/main/java/com/example/boot/service/impl/TransactionServiceImpl.java
> +        Account accountFrom = accountRepository.findByAccountNumber(accountFromNumber).get();
add annotation Transaction for this method

2021-03-02 13:55 UTC, YuraBondarenko commented on src/main/java/com/example/boot/model/Account.java
> +    private double balance;
remake everywhere to BigDecimal

2021-03-02 14:19 UTC, YuraBondarenko approved these changes

2021-03-03 07:14 UTC, boroda4436 requested changes

2021-03-03 07:14 UTC, boroda4436 commented on src/main/java/com/example/boot/util/Converter.java
> +public class Converter {
This is not a part of the current HW

2021-03-03 07:14 UTC, boroda4436 commented on src/main/java/com/example/boot/util/Converter.java
> +    public static BigDecimal convert(BigDecimal amount, Currency from, Currency to) {
static methods are evil

2021-03-03 09:10 UTC, KseniiaMakarova requested changes

2021-03-03 09:10 UTC, KseniiaMakarova commented on src/main/java/com/example/boot/service/impl/AccountServiceImpl.java
> +        accountRepository.save(account);
представь, что у тебя расширится функционал, и нужно будет с контроллера не только заблокировать юзера, но и обратно сделать активным, или будет отдельный ендпойнт для изменения емейла юзеру

Тогда тебе придется каждый раз дописывать метод для сервиса
Лучше дизайнить api (слой сервиса) таким образом, чтобы были многофункциональные методы, которые клиент может использовать по нескольку раз

поэтому мне кажется, лучше поместить логику `account.setActive(false);` в контроллер, и потом вызывать accountService.save()

2021-03-03 09:10 UTC, KseniiaMakarova commented on src/main/java/com/example/boot/service/impl/TransactionServiceImpl.java
> +
redundant empty line

2021-03-03 09:10 UTC, KseniiaMakarova commented on src/main/java/com/example/boot/service/impl/TransactionServiceImpl.java
> +                    + accountFrom + " to transfer: " + amount + accountFrom.getCurrency());
it will be great to use `String.format` in such cases

2021-03-03 09:10 UTC, KseniiaMakarova commented on src/main/java/com/example/boot/service/impl/TransactionServiceImpl.java
> +                .date(LocalDateTime.now())
why is outcoming transaction registered later than incoming? maybe it is better to register them at one time?

2021-03-03 09:10 UTC, KseniiaMakarova commented on src/main/java/com/example/boot/service/impl/TransactionServiceImpl.java
> +        accountRepository.save(accountTo);
were the balances changed?

2021-03-03 09:10 UTC, KseniiaMakarova commented on src/main/java/com/example/boot/service/impl/TransactionServiceImpl.java
> +import javax.transaction.Transactional;
let's use org.springframework.transaction.annotation.Transactional

2021-03-03 11:48 UTC, KseniiaMakarova approved these changes

2021-03-03 11:53 UTC, merged